appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Mpvwz+cS8eUCu2c0oVsTuR+ikKUMBROnKfytBrky5YVbRGF/Lmip78utRnrjC+/jMf7b/50AZjQx5DXGe+j4Mdru4k6yS2o0mJHD+E+/HGKEVg4pkdiGDgSsXllpRwbOj5edoKOm51BfVQaq1yViE5+KcSud3rcotUkiVqR/IWGqMG6Ntgd0HDyjz3SNjVMDJnvNPWrmyxja8vUpFzVgOFJktj2E5ZBFBw4b420HAQg0dGIS5SSz5DOg960mda88mTvlz6G5mhAs07LsztMjye1CPWwyhjf6N2qv9r4WJuaBkel/F9B7YfQ15RPye4mvkfvT2bgJ6j60HbqXFRxv5jBGts7gKa5+kIzUNzWy2PL4HIwFeQBQ06zYh39qMyehpXWPPAcRvQCnD23/Lztom50YW0TCJ4KMnHsDfJogXLoyApRun3t6iJSKBLrc/mkx4geWgtEhczOI3V8i2noO9rTpiiAF/zBy87iEUwIBLESAR4IcJtBq91Yk1QifXhsNlndmycGKZ9sVbCDnSBLnKk9mfL1Gy3//ZsCjUpl8Jfimn0rxkEhdpYrKZkULJ6B6M2wP5zqD3G2Jftv8vTtYcy1aJBxJnEaw0tHwjDgQArJFDbYN47eJyhG4aQENGRjY8HgPRazT4DjfJ//64CFCFY3axybTgpqGvvyu+9bGL9c=
conda_forge_output_validation: false
